function T = T_leg(in1,in2)
%T_leg
%    T = T_leg(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Oct-2022 21:44:54

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
Ir = in2(9,:);
N = in2(10,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = N.^2;
t4 = dth1.^2;
t5 = dth2.^2;
t6 = l_AC.^2;
t7 = l_A_m3.^2;
t8 = l_B_m2.^2;
t9 = l_OA.^2;
et1 = (I1.*t4)./2.0+(I2.*t4)./2.0+(I2.*t5)./2.0+(I3.*t4)./2.0+(I3.*t5)./2.0+(I4.*t4)./2.0+(Ir.*t4)./2.0+(l_C_m4.^2.*m4.*t4)./2.0+(l_OB.^2.*m2.*t4)./2.0+(l_O_m1.^2.*m1.*t4)./2.0+I2.*dth1.*dth2+I3.*dth1.*dth2+(Ir.*t3.*t4)./2.0+(Ir.*t3.*t5)./2.0+(m2.*t4.*t8)./2.0+(m3.*t4.*t7)./2.0+(m4.*t4.*t6)./2.0+(m2.*t5.*t8)./2.0+(m3.*t5.*t7)./2.0+(m4.*t5.*t6)./2.0+(m3.*t4.*t9)./2.0+(m4.*t4.*t9)./2.0+dth1.*dth2.*m2.*t8+dth1.*dth2.*m3.*t7+dth1.*dth2.*m4.*t6+l_C_m4.*l_OA.*m4.*t4+Ir.*N.*dth1.*dth2+l_AC.*l_C_m4.*m4.*t2.*t4+l_AC.*l_OA.*m4.*t2.*t4+l_A_m3.*l_OA.*m3.*t2.*t4+l_B_m2.*l_OB.*m2.*t2.*t4;
et2 = dth1.*dth2.*l_AC.*l_C_m4.*m4.*t2+dth1.*dth2.*l_AC.*l_OA.*m4.*t2+dth1.*dth2.*l_A_m3.*l_OA.*m3.*t2+dth1.*dth2.*l_B_m2.*l_OB.*m2.*t2;
T = et1+et2;
