function A = A_doublepend(in1,in2)
%A_doublepend
%    A = A_doublepend(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Sep-2022 23:33:40

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(1,:);
c2 = in2(2,:);
l1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = m2.*t3;
t5 = c2.*l1.*m2.*t2;
t6 = I2+t4+t5;
A = reshape([I1+t5+t6+c1.^2.*m1+l1.^2.*m2,t6,t6,I2+t4],[2,2]);
