function b = b_cartpend(in1,in2,in3)
%B_CARTPEND
%    B = B_CARTPEND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Sep-2022 22:36:46

F = in2(1,:);
c = in3(1,:);
dth = in1(4,:);
g = in3(10,:);
k = in3(6,:);
kappa = in3(7,:);
l = in3(2,:);
l0 = in3(8,:);
m2 = in3(4,:);
tau = in2(2,:);
th = in1(2,:);
th0 = in3(9,:);
x = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = l.^2;
t5 = x.^2;
t6 = l.*t3.*x.*2.0;
t7 = t4+t5+t6;
t8 = sqrt(t7);
t9 = 1.0./t8;
t10 = -t8;
t11 = l0+t10;
b = [F+(k.*t9.*t11.*(x.*2.0+l.*t3.*2.0))./2.0+c.*dth.^2.*m2.*t3;tau-(kappa.*(th.*2.0-th0.*2.0))./2.0+F.*l.*t2-c.*g.*m2.*t3+k.*l.*t2.*t9.*t11.*x];
