function E = energy_cartpend(in1,in2)
%ENERGY_CARTPEND
%    E = ENERGY_CARTPEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Sep-2022 22:36:46

I2 = in2(5,:);
c = in2(1,:);
dth = in1(4,:);
dx = in1(3,:);
g = in2(10,:);
k = in2(6,:);
kappa = in2(7,:);
l = in2(2,:);
l0 = in2(8,:);
m1 = in2(3,:);
m2 = in2(4,:);
th = in1(2,:);
th0 = in2(9,:);
x = in1(1,:);
t2 = cos(th);
t3 = dth.^2;
t4 = dx.^2;
E = (I2.*t3)./2.0+(m1.*t4)./2.0+(m2.*t4)./2.0+(kappa.*(th-th0).^2)./2.0+(k.*(l0-sqrt(l.^2+x.^2+l.*x.*sin(th).*2.0)).^2)./2.0+(c.^2.*m2.*t3)./2.0-c.*g.*m2.*t2+c.*dth.*dx.*m2.*t2;
