function E = energy_doublepend(in1,in2)
%ENERGY_DOUBLEPEND
%    E = ENERGY_DOUBLEPEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Sep-2022 23:33:40

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(1,:);
c2 = in2(2,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(9,:);
l1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = c2.^2;
t5 = dth1.^2;
t6 = dth2.^2;
E = (I1.*t5)./2.0+(I2.*t5)./2.0+(I2.*t6)./2.0+(c1.^2.*m1.*t5)./2.0+(l1.^2.*m2.*t5)./2.0-g.*m2.*(l1.*t2+c2.*cos(th1+th2))+I2.*dth1.*dth2+(m2.*t4.*t5)./2.0+(m2.*t4.*t6)./2.0+dth1.*dth2.*m2.*t4-c1.*g.*m1.*t2+c2.*l1.*m2.*t3.*t5+c2.*dth1.*dth2.*l1.*m2.*t3;
