function keypoints = keypoints_cartpend(in1,in2)
%KEYPOINTS_CARTPEND
%    KEYPOINTS = KEYPOINTS_CARTPEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    27-Sep-2022 22:36:46

c = in2(1,:);
l = in2(2,:);
th = in1(2,:);
x = in1(1,:);
t2 = cos(th);
t3 = sin(th);
keypoints = reshape([x,0.0,x+c.*t3,-c.*t2,x+l.*t3,-l.*t2],[2,3]);
