function A = A_jumping_leg(in1,in2)
%A_jumping_leg
%    A = A_jumping_leg(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Dec-2022 21:59:00

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(2,:);
c2 = in2(3,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = c1.^2;
t5 = t2.^2;
t6 = c1.*m1.*t2;
t7 = c2.*t2.*2.0;
t8 = l.*t2.*2.0;
t9 = mh.*t8;
t10 = t7+t8;
t11 = (m2.*t10)./2.0;
t12 = t6+t9+t11;
A = reshape([m1+m2+mh,t12,t12,I1+I2+(m1.*(t4.*t5.*2.0+t3.^2.*t4.*2.0))./2.0+(m2.*((c2.*t2+l.*t2).^2.*2.0+(c2.*t3-l.*t3).^2.*2.0))./2.0+l.^2.*mh.*t5.*4.0],[2,2]);
