function b = b_jumping_leg(in1,tau,Fy,in4)
%B_JUMPING_LEG
%    B = B_JUMPING_LEG(IN1,TAU,Fy,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Dec-2022 21:59:00

c1 = in4(2,:);
c2 = in4(3,:);
dth = in1(4,:);
dy = in1(3,:);
g = in4(9,:);
l = in4(1,:);
m1 = in4(4,:);
m2 = in4(5,:);
mh = in4(6,:);
th = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = c1.^2;
t5 = dth.^2;
t6 = c2.*t2;
t7 = l.*t2;
t8 = c2.*t3;
t9 = l.*t3;
t10 = c1.*dth.*t2;
t11 = dth.*t7.*2.0;
t12 = -t7;
t13 = -t9;
t14 = dy+t10;
t16 = t6+t7;
t17 = t8+t9;
t15 = dy+t11;
t18 = dth.*t16;
t19 = t6+t12;
t20 = t8+t13;
t21 = dy+t18;
b = [Fy-g.*m1-g.*m2-g.*mh+dth.*(dth.*m2.*t17+dth.*mh.*t9.*2.0+c1.*dth.*m1.*t3);tau+dth.*((m2.*(t17.*t18.*2.0+t17.*t21.*2.0-dth.*t19.*t20.*4.0))./2.0+(m1.*(c1.*t3.*t14.*2.0-dth.*t2.*t3.*t4.*2.0))./2.0+mh.*t9.*t15.*2.0+dth.*mh.*t7.*t9.*4.0)-(m1.*(c1.*dth.*t3.*t14.*2.0-t2.*t3.*t4.*t5.*2.0))./2.0-(m2.*(dth.*t17.*t21.*2.0-t5.*t19.*t20.*2.0))./2.0-g.*m2.*t16-g.*mh.*t7.*2.0-c1.*g.*m1.*t2-dth.*mh.*t9.*t15.*2.0];
