function C = C_jumping_leg(in1,tau,in3)
%C_jumping_leg
%    C = C_jumping_leg(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Dec-2022 21:59:01

y = in1(1,:);
C = y;
