function COM = COM_jumping_leg(in1,in2)
%COM_jumping_leg
%    COM = COM_jumping_leg(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Dec-2022 21:59:01

c1 = in2(2,:);
c2 = in2(3,:);
dth = in1(4,:);
dy = in1(3,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th = in1(2,:);
y = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t6 = m1+m2+mh;
t4 = c2.*t2;
t5 = l.*t2;
t7 = c2.*t3;
t8 = l.*t3;
t9 = c1.*m1.*t2;
t10 = 1.0./t6;
COM = [t10.*(t9-m2.*(t4-t5));t10.*(mh.*(t8.*2.0+y)+m2.*(t7+t8+y)+m1.*(y+c1.*t3));dth.*t10.*(m2.*(t7-t8)-c1.*m1.*t3);dy+dth.*t10.*(t9+m2.*(t4+t5)+mh.*t5.*2.0)];
