function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    07-Dec-2022 21:59:00

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(2,:);
c2 = in2(3,:);
dth = in1(4,:);
dy = in1(3,:);
g = in2(9,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th = in1(2,:);
y = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = dth.^2;
t5 = c2.*t3;
t6 = l.*t3;
E = (I1.*t4)./2.0+(I2.*t4)./2.0+(m1.*((dy+c1.*dth.*t2).^2+c1.^2.*t3.^2.*t4))./2.0+(mh.*(dy+dth.*l.*t2.*2.0).^2)./2.0+(m2.*((dy+dth.*(c2.*t2+l.*t2)).^2+t4.*(t5-t6).^2))./2.0+g.*m1.*(y+c1.*t3)+g.*mh.*(t6.*2.0+y)+g.*m2.*(t5+t6+y);
